name: prudencefontaine
favicon: null
layout_spectrum: 0.00371
typography_spectrum: 0.11661479924805462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#040404'
    - '#676767'
    - '#8d8d8d'
    - '#4d4d4d'
  brandStrength: 0.04192485986277461
  lightness: 0.5
  saturation: 0.048513202695176005
  rhythmicContrast: 0.6491636943537742
purpose: []
